### ISSUE TITLE
Add Spec Ops Team

### ISSUE THREAD

**Issue by GenericSubject** [jokoho48/AWPublicMission#14]
Super Trooper Spec Ops Team to the max:
Traits:
- low equipment weight / high mobility
- silenced+allrounder weaponry
- Laser marking
- shortrange OW services as surrogation for the designated sniper team
- infiltration of Enemy positions
- [x] Team Leader
- [x] ARMan
- [x] AT
- [x] AA
- [x] Grenadier
- [x] Marksman
- [x] Specialist
- [x] Trooper

Light Team:
- [x] Team Leader
- [x] ARMan
- [x] AT
- [x] AA
- [x] Grenadier
- [x] Marksman
- [x] Specialist
- [x] Trooper

**Comment by jokoho48** [comment]
Loadouts todo
- [ ] Team Leader
- [ ] ARMan
- [ ] AT
- [ ] ULG
- [ ] Marksman
- [ ] Specialist
