### ISSUE TITLE
Base Fire Protection too Big

### ISSUE THREAD

**Issue by GenericSubject** [jokoho48/AWPublicMission#27]
Big radius of Base Protection leads to:
- being defenseless against Ki engages from patrol and near by citys like in the saturday mission we saw at 31.10., were the Konvoi got attacked
- protection should be only in the inner areas of the base and not on the whole airfield

another Problem:
- if we make the radius smaller, ki patrols may enter the airfield 

Suggestet Solution until we rework Ki Patrols:
- add a second marker radius sized only to protect the inner base

**Comment by jokoho48** [comment]
isses get closed with Merged PR
