### ISSUE TITLE
Luftabwehrschützten

### ISSUE THREAD

**Issue by jokoho48** [jokoho48/AWPublicMission#31]
Da wir keine Lufthoheit haben sollten wir überlegen auch Luftabwehrschützen Loadouts mit einzufügen

**Comment by simon84** [comment]
Find ich eine gute Idee. Muss die Mission nur dahingehend bearbeitet werden, dass auch ein Luftangriff (Helicopter oder vielleicht sogar mal Jets) ausgeführt wird.

**Comment by jokoho48** [comment]
https://github.com/jokoho48/AWPublicMission/commit/4833bb8eac8a2d0ff6ea8885faea0d7a1314d0da
schon getan daher brauchen wir es ja auch
und ansich war schon immer die möglichkeit das helis uns überraschen

**Comment by GenericSubject** [comment]
Hatte ich auch schon vor ner weile überlegt, wollte die guten alten Stinger Schützen wieder reinbringen.
DIe müssten bei Tf-47 Launchers auch dabei sein.
Hatte mir aber zunächst überlegt, lass die Leute noch ein bssl Skillshoten mit der At4/M3/Smaw, damits bssl schwerer ist : )

Naja ich nimm die mal rein und schaue wie die resonanz ist.

**Comment by jokoho48** [comment]
in RHS ist die Stinger mit drinne die einfach benutzten
