### ISSUE TITLE
Glock 17 Advanced Ballistics Error

### ISSUE THREAD

**Issue by GenericSubject** [jokoho48/AWPublicMission#33]
File: z\ace\addons\advanced_ballistics\functions\fnc_calculateAmmoTemperatureVelocityShift.sqf, line 9

Error in expression <eUpperLimit = _muzzleVelocityShiftTable select 10;
if (isNil "_muzzleVelocityShi>

Error position: <select 10;
if (isNil "_muzzleVelocityShi>
Error Nullteiler

**Comment by GenericSubject** [comment]
workaround: using vanilla pistol for SOF ?

**Comment by jokoho48** [comment]
yes ACE Issue
this is a wont fix
