### ISSUE TITLE
Visiere-Nacht

### ISSUE THREAD

**Issue by GenericSubject** [jokoho48/AWPublicMission#48]
- Visiere  Nachtsichttauglich machen.

**Comment by jokoho48** [comment]
also ansich als Marksman denke ich nein und für das EoTech MG "rhsusf_acc_eotech_552"

der rest hat schon welche

**Comment by GenericSubject** [comment]
was ist mit dem vanilla nachtsichtvisier für den marksman ? Ansonsten muss der marksman halt mit iron sight auskommen, das würde dann einen erhöhter Schwieriegkeitsgrad für sniper darstellen.

**Comment by jokoho48** [comment]
nein Marksman benuzt man in der nacht nicht so finde ich das

**Comment by GenericSubject** [comment]
naja ich bin zumindest für die ironsight sache, sonst wiedersprichst du ja deinem eigenen Argument der vielfältigkeit, ich wüsste auch nicht was gegen nachtsichtvisier für marksman spricht abgesehen vom caching

**Comment by jokoho48** [comment]
caching ist da egal es ändert sich nichts bei tag oder nacht das ist komplett gleich jedoch denke ich das wir schauen sollten ob es überhaubt realistisch ist ein Marksmanrifle zuhaben wo das Visier Nachtsicht hat ich denke nicht und wir haben eh das DMS als visier wenn ich mich nicht irre da ist nen red dot oben drauf das reicht aus
