### ISSUE TITLE
BFT Bad conversion: array

### ISSUE THREAD

**Issue by GenericSubject** [jokoho48/AWPublicMission#57]
4:49:55 Bad conversion: array
 4:49:55 Error in expression <findDisplay 12) displayCtrl 51);
{
_map drawIcon _x;
} forEach BG_BFT_Icons;

>  4:49:55   Error position: <drawIcon _x;
> } forEach BG_BFT_Icons;
> 
>  4:49:55   Error 0 Elemente angegeben, 3 erwartet
>  4:49:55 File mpmissions__CUR_MP.Altis\lib\bft_light\fn_drawEvent.sqf, line 18

**Comment by simon84** [comment]
Unter welcher Bedingung ist der Fehler aufgetreten?

**Comment by jokoho48** [comment]
also ich hatte ihn auch aber nur einmal und ich konnte es auch nicht reproduzieren. es kommt mir so vor als ob man nen objNull oder ne controlNull hat und das irgendwie nen fehler auswirft

**Comment by simon84** [comment]
Kann es sein, dass wenn ein GroupLeader disconnected dieser Fehler auftritt? Dann befindet sich ein objNull im Array. Das könnte ich aber abfangen.

**Comment by GenericSubject** [comment]
Kann ich leider auch nicht genau sagen, man muss wissen das wir allerdings nur zu dritt auf dem server waren und explosives und  reperatur und neue helis in der basis getestet haben. Meine das zu dem Zeitpunkt des Fehlers niemand rausgegangen ist.

**Comment by jokoho48** [comment]
ist denn jemand respawned? ich bin mir gerade unsicher
