### ISSUE TITLE
Loadout Diver

### ISSUE THREAD

**Issue by Gaspasar** [jokoho48/AWPublicMission#62]
The Diver has
1x Banana 
2x NS Visions
1x Binocular
1x Vector

is this meant to be so?

**Comment by GenericSubject** [comment]
Hey, Gaspasar
Thx for the hint, will give him nv in the right slot. The Thing is if you change your loadeout, you will keep your items if the slot of the new loadout is empty, like you keep pilot glasses or diver glasses cuz most other classes don't have sth on this slot. It looked a strange with nv on so i put them in backpack. If their is a high demand for divers i can also make a whole diver team, but i guess right now with most missions in the countryside divers wont be used very often.

**Comment by jokoho48** [comment]
@GenericSubject status?

**Comment by GenericSubject** [comment]
could not find the Diver in the db ? where did he go ?

**Comment by jokoho48** [comment]
fixed
