### ISSUE TITLE
Add Logistic Gear

### ISSUE THREAD

**Issue by jokoho48** [jokoho48/AWPublicMission#65]
Seit dem wir Cargo Kisten und Repair/Ammo/Fuel Fahrzeuge hat sollte man mal darüber nachdenken ein Logistker hinzu zufügen

**Comment by GenericSubject** [comment]
stimmt ist eine Überlegung wert, im rl gibts auch analog nen bsp für zivile Mitarbeiter die in dem Bereich eingesetzt werden, zwar eine Grundausbildung für Selbstverteidigung in Kriesengebieten erhalten aber nicht als Kampfeinheiten eingsetzt werden soweit ich weiß andere Idee wäre einfach Soldaten spezialisiert auf Logistik mit reduzierter Kampfausrüstung.
