### ISSUE TITLE
better Vehicle Repair Field for Airplanes / fix Sell Field for A10a

### ISSUE THREAD

**Issue by Gaspasar** [jokoho48/AWPublicMission#67]
- Würde mir ein praktischeres Vehicle Repair Field für die A10a wünschen.
  Eines durch das man hindurch fahren kann, beim vorhandenen ist der Wende Kreis doch sehr schmal, und man muss in der Wiese wenden. Eventuell einfach ein zusätzliches vorne am Terminal Vorplatz zum durchfahren.
- Auf dem Vorhanden vehicle Spawn Feld kann man die A10a nicht verkaufen.
  nur durch den Neukauf eines anderen Fahrzeuges wird die platzierte A10a automatisch verkauft.

**Comment by jokoho48** [comment]
fixed https://github.com/jokoho48/AWPublicMission/commit/5b4b20f5c2b1a0d55bd9e76acf6511583d2faa8a
