### ISSUE TITLE
random/changeable  Time and Weather

### ISSUE THREAD

**Issue by Gaspasar** [jokoho48/AWPublicMission#72]
Würde mir mehr Abwechslung beim Wetter und der Uhrzeit wünschen.
Entweder Zufällig beim starten der Mission, oder veränderbar während der mission.

Vielleicht kann man ja zum beispiel ein einstellbareres Schild aufstellen.
Würde so etwas mehr abwechslung geben.
Ich weiß regen zieht performance, aber vielleicht kriegt man es ja bewölkter.

**Comment by jokoho48** [comment]
ich denke ehr das ich das nicht machen werde da es hier Performance oder Sync Probleme geben kann

**Comment by Gaspasar** [comment]
Das bezieht sich auf wetter oder?

Hab ich auch schon von anderen gehört, wetter ist wohl was lokales. 
Aber wäre eine zufällige startzeit möglich?
Also wenn die mission gestartet wird?
Vielleicht 3-4 verschiedene startzeiten möglich, die zufälllig ausgewählt werden?
- mittag
- Nacht (2 std vor morgengrauen)
- morgengrauen
- abends (2std vor sonnen untergang)

Immoment erleben wir den sonnenuntergang leider so gut wie nie, und ich find arma bietet schöne tag/nacht wechsel.

**Comment by jokoho48** [comment]
die Mission Startet um eine zufällige Uhrzeit :D einfach mal testen ;)
