### ISSUE TITLE
Remove Blackout/Redout

### ISSUE THREAD

**Issue by ClemensKrug** [jokoho48/AWPublicMission#82]
Ich fände es besser, wenn die G-Effekte von ACE deaktiviert werden würden. Natürlich ist das realistischer, nimmt aber meiner Meinung nach viel vom Spielspaß, wenn man tatsächlich mal CAS mit der A10, etc fliegen will.  Muss man natürlich sehen ob diese Meinung geteilt wird.

**Comment by F4BI** [comment]
Wenn ich überlege wie oft CAS überhaupt eingesetzt wird glaube ich nicht das es einen Unterschied machen wird.
Der Blackout/Redout tritt doch nur in "extremen" Flugmanövern auf oder? Da diese im CAS normalerweise nicht vorkommen sehe ich keine Vorteile darin die Effekte abzuschalten.

**Comment by ClemensKrug** [comment]
Naja, ich persönlich würde viel öfter CAS fliegen, wenn es keine Red/Blackouts gäbe. Und sie treten meiner Meinung nach relativ schnell auf. Die Frage ist, gäbe es Nachteile? Also für mich wäre es ein Vorteil. Wwenn es niemanden gibt, der die Effekte umbedingt haben will, spräche nichts dagegen sie rauszunehmen.

**Comment by F4BI** [comment]
Joko dein Part

**Comment by jokoho48** [comment]
wont fix ist entweder an oder aus
die Blackout werte sind realistisch und können aktuell nicht angepasst werden. das problem ist halt nur das ArmA viel zu Starke/Heftige Manover Möglich sind ;) d.h. einfach enspannter fliegen
