### ISSUE TITLE
Add New ACE Items to Loadouts

### ISSUE THREAD

**Issue by jokoho48** [jokoho48/AWPublicMission#87]
New ACE Items: 
"ACE_EntrenchingTool" - To Dig Envelopes
"ACE_SpraypaintBlack"/"ACE_SpraypaintRed"/"ACE_SpraypaintGreen"/"ACE_SpraypaintBlue" - To Mark/Tagg a Position or Mark/Tagg Buildings while house Clearing

**Comment by F4BI** [comment]
All Leaders get Spraypaint
Rifleman get EntrenchingTool until engineer exits
